# Generated by Django 4.2.2 on 2023-06-23 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_adder',
            field=models.CharField(default='nexisClo', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(250), django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='U', max_length=50),
        ),
    ]
