# Generated by Django 4.2.2 on 2023-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_product_adder_alter_product_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=69)),
                ('phone', models.CharField(default='', max_length=18)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
