# Generated by Django 4.2.2 on 2023-06-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
