# Generated by Django 4.2.2 on 2023-06-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
