# Generated by Django 4.2.2 on 2023-06-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
