# Generated by Django 4.2.2 on 2023-06-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(default=0),
        ),
    ]
