# Generated by Django 4.2.2 on 2023-06-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_order_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_amount',
            new_name='amount',
        ),
    ]
